name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Prepare Project Structure and Build
      run: |
        mkdir -p app/src/main/java/com/example/otp_app
        [ -f AndroidManifest.xml ] && mv AndroidManifest.xml app/src/main/ || true
        [ -f SmsReceiver.java ] && mv SmsReceiver.java app/src/main/java/com/example/otp_app/ || true
        [ -f build.gradle ] && mv build.gradle app/ || true
        
        if [ ! -f "settings.gradle" ]; then
          echo "include ':app'" > settings.gradle
        fi

        if [ ! -f "./gradlew" ]; then
          gradle wrapper
        fi
        
        chmod +x gradlew || true
        ./gradlew assembleDebug
        
